### ISSUE TITLE
default exported version

### ISSUE THREAD

**Issue by linonetwo** [infeng/vscode-react-typescript#18]
Currently, it's exported.

But if one file only contains one function, it should be default exported.

**Comment by infeng** [comment]
Welcome pr.

**Comment by linonetwo** [comment]
I just wanna discuss, do you think it's ok to change all current snippet to add `default`,
Or it's better to copy paste current snippets, with an additional `d` in the prefix?

**Comment by infeng** [comment]
It looks like this is the only [one](https://github.com/infeng/vscode-react-typescript/blob/master/snippets/snippets.json#L113) that hasn't been default exported.

**Comment by linonetwo** [comment]
Oh....Actually it is the only snippet I'm using...SO...

PR is here: https://github.com/infeng/vscode-react-typescript/pull/20
